version: '3.8'

services:
  manager:
    image: alpine:3.21.2
    command: ["sh", "-c", "echo 'Manager service running'"]
    networks:
      - shared_network

networks:
  shared_network:
    external: true