version: '3.8'
services:
  weight_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${PROJECT_NAME}_weight_app
    volumes:
      - ./src/in:/app/in     
    ports:
      - "${APP_PORT_MAPPING}:5000"
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${MYSQL_HOST}:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  mysql:
    image: mysql:8.0
    container_name: ${PROJECT_NAME}_mysql_weight_db
    ports:
      - "${DB_PORT_MAPPING}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "${MYSQL_HOST}"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - mysql_weight_data:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql

volumes:
  mysql_weight_data: