# docker-compose.yml
version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: weight
      MYSQL_USER: weight_user
      MYSQL_PASSWORD: weight_pass
    ports:
      - "3306:3306"
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  weight_service:
    build: .
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: weight_user
      MYSQL_PASSWORD: weight_pass
      MYSQL_DATABASE: weight
    ports:
      - "5000:5000"
    depends_on:
      mysql:
        condition: service_healthy

